-- =============================================================================
-- E2B Self-Hosted Seed Data
-- =============================================================================
-- This script inserts the minimum data needed to operate the API server:
--   1. A tier (defines resource limits)
--   2. A team (organizational unit)
--   3. An API key (for authenticating SDK/API requests)
--
-- IMPORTANT: The API key row requires a SHA-256 hash. You cannot simply paste
-- a raw key here. Use the generate_api_key.go tool to produce both the raw
-- key (for your .env / SDK config) and the corresponding SQL INSERT with the
-- correct hash.
--
-- Usage:
--   1. Run migrations first (goose up)
--   2. Generate API key:
--        cd aws/db && go run generate_api_key.go
--      This prints the raw key AND the INSERT statement.
--   3. Paste the generated INSERT statement below (or pipe it to psql).
--   4. Run this file:
--        psql "$DATABASE_URL" -f seed.sql
-- =============================================================================

-- Step 1: Create the "base_v1" tier if it does not exist.
-- This tier defines the resource limits for teams.
-- After migration 20250901161352, tiers has columns:
--   id, name, disk_mb, concurrent_instances, max_length_hours, max_vcpu, max_ram_mb, concurrent_template_builds
INSERT INTO public.tiers (id, name, disk_mb, concurrent_instances, max_length_hours, max_vcpu, max_ram_mb, concurrent_template_builds)
VALUES ('base_v1', 'Base', 512, 20, 24, 8, 8192, 20)
ON CONFLICT (id) DO NOTHING;

-- Step 2: Create the self-hosted team.
-- After migration 20260309120000, teams has columns:
--   id, created_at, is_blocked, name, tier, email, is_banned, blocked_reason, cluster_id, sandbox_scheduling_labels, slug
-- Note: is_default was removed in migration 20250106142106.
-- Note: slug is auto-generated by trigger from migration 20260121175429 if left NULL,
--       but we provide it explicitly to be deterministic.
INSERT INTO public.teams (id, name, tier, email, slug)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'self-hosted',
    'base_v1',
    'admin@e2b.local',
    'self-hosted'
)
ON CONFLICT (id) DO NOTHING;

-- Step 3: Insert API key.
-- =============================================================================
-- DO NOT write a raw key here. The team_api_keys table stores ONLY hashes.
-- After the final schema (migration 20250910124212 removed raw key column),
-- the required columns are:
--
--   id              uuid     (auto-generated)
--   team_id         uuid     (references teams.id)
--   api_key_hash    text     (SHA-256 hash with $sha256$ prefix, base64 encoded)
--   api_key_prefix  varchar  (always 'e2b_')
--   api_key_length  integer  (always 40 -- hex encoding of 20 random bytes)
--   api_key_mask_prefix varchar (first 2 hex chars of key value)
--   api_key_mask_suffix varchar (last 4 hex chars of key value)
--   name            text     (human-readable name)
--   created_at      timestamptz (default CURRENT_TIMESTAMP)
--   updated_at      timestamptz (nullable)
--   last_used       timestamptz (nullable)
--   created_by      uuid     (nullable, references auth.users)
--
-- Run the key generator to get the correct INSERT:
--
--   cd aws/db && go run generate_api_key.go
--
-- Example output (DO NOT USE THIS -- generate your own):
--
--   INSERT INTO public.team_api_keys (team_id, api_key_hash, api_key_prefix, api_key_length, api_key_mask_prefix, api_key_mask_suffix, name)
--   VALUES ('00000000-0000-0000-0000-000000000001', '$sha256$abc...xyz', 'e2b_', 40, 'ab', 'wxyz', 'Default API Key');
--
-- Paste the generated INSERT below this line:
-- =============================================================================
